### ISSUE TITLE
Zoom in different views

### ISSUE THREAD

**Issue by itaca9** [denis-gorin/brackets_zw#1]
Hi! This app is really useful, so thanks for that :1st_place_medal: 

A question or an idea, is it possible to have different zoom in different views? Because in brackets it is possible to split the screen, so that option would be interesting

Thanks :)

**Comment by denis-gorin** [comment]
Hi, I think everything is possible, but, unfortunately, the Brackets was died for me at the moment when Extract was detached from it...
